application: xuanji
version: 1
runtime: python
api_version: 1

handlers:
- url: /python/css
  static_dir: css
  
- url: /static
  static_dir: static
  
- url: /lectures
  static_files: leech.html
  upload: what is this
  
- url: /css
  static_dir: css
  
- url: /python/ace
  static_dir: ace

- url: /.*
  script: index.py
